Added new standup log
HTTP5214-Winter2023/starter pull request #32
Opened 2023-02-21 23:44 UTC by Byounes123321

Hello @beartisan would you please do me the biggest favour of all time and merge this for me 
Thank you!

2023-03-08 18:44 UTC, beartisan approved these changes

2023-03-08 18:45 UTC, beartisan approved these changes

2023-03-08 18:47 UTC, beartisan requested changes
done

2023-04-19 18:27 UTC, EllisChang97 approved these changes
well done

2023-04-19 18:27 UTC, closed without merging